name: activity_recognition
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - astor=0.8.1
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attrs=24.2.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cachetools=5.3.3
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.0.5
  - cryptography=43.0.0
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - eigen=3.4.0
  - executing=0.8.3
  - expat=2.6.3
  - ffmpeg=4.2.2
  - flatbuffers=2.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - gast=0.4.0
  - getopt-win32=0.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - google-auth=2.29.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gts=0.7.6
  - h5py=2.10.0
  - harfbuzz=4.3.0
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.7
  - imageio=2.36.0
  - imageio-ffmpeg=0.5.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - keras=2.4.3
  - keras-applications=1.0.8
  - keras-base=2.4.3
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libclang13=14.0.6
  - libcurl=8.9.1
  - libdeflate=1.17
  - libffi=3.4.4
  - libgd=2.3.3
  - libglib=2.78.4
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - moviepy=1.0.3
  - multidict=6.0.4
  - nest-asyncio=1.6.0
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.2
  - opencv=4.6.0
  - openjpeg=2.5.2
  - openssl=3.3.2
  - opt_einsum=3.3.0
  - packaging=24.1
  - pango=1.50.7
  - parso=0.8.3
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - poppler=24.09.0
  - poppler-data=0.4.11
  - proglog=0.1.10
  - prompt-toolkit=3.0.43
  - protobuf=3.20.3
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydot=3.0.1
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pyopenssl=24.2.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyreadline=2.1
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python-flatbuffers=24.3.25
  - python_abi=3.8
  - pywin32=305
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rsa=4.7.2
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.6.0
  - termcolor=2.1.0
  - threadpoolctl=3.5.0
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.5
  - werkzeug=3.0.3
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - wrapt=1.14.1
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.11.0
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - opencv-python==4.10.0.84
